#!/usr/bin/env python3
"""
setup_wizard.py - Interactive CLI Setup Wizard for pico-fan-control
====================================================================
Guided setup wizard that:
  1. Scans /dev/serial/by-id/ for Pico / RP2040 devices
  2. Displays detected boards with protocol response status
  3. Allows selection of the target Pico device
  4. Tests the external fan across various duty cycles
  5. Scans and selects available internal fans (hwmon + /proc/acpi/ibm/fan)
  6. Saves configuration to /etc/pico-fan/config.json
"""

from __future__ import annotations

import os
import sys
import json
import time
import shutil
import signal
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

# Add CLI and daemon directories to module search path
SCRIPT_DIR = Path(__file__).parent.resolve()
DAEMON_DIR = SCRIPT_DIR.parent / "daemon"
sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(DAEMON_DIR))

from ANSI_colors import BOLD, CYAN, DIM, GREEN, RED, RESET, WHITE, YELLOW, cformat, cprint, cwrite

try:
    from hardware_detector import scan_devices, PicoDevice
    from pico_adapter import PicoAdapter
    from fan_daemon import (
        read_internal_rpm_ibm,
        read_internal_rpm_hwmon,
    )
    from version import __version__
except ImportError as e:
    cprint(f"Errore di importazione moduli daemon: {e}", RED)
    cprint("Assicurarsi che il pacchetto sia installato correttamente.", RED)
    sys.exit(1)

import serial.serialutil

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
CONFIG_DIR  = "/etc/pico-fan"
CONFIG_FILE = "/etc/pico-fan/config.json"
UDEV_RULE_FILE = "/etc/udev/rules.d/99-pico-fan-device.rules"


def start_service() -> bool:
    """Enables and starts the systemd service after configuration is saved."""
    try:
        subprocess.run(
            ["systemctl", "enable", "--now", "pico-fan.service"],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except FileNotFoundError:
        cprint("⚠ systemd non disponibile: servizio non avviato.", YELLOW)
        return False
    except subprocess.CalledProcessError:
        cprint(
            "⚠ Impossibile abilitare/avviare il servizio systemd.\n"
            "  Verificare lo stato con: sudo systemctl status pico-fan",
            YELLOW,
        )
        return False

    cprint("✓ Servizio pico-fan abilitato e avviato.", GREEN)
    return True


def configure_udev(device: PicoDevice) -> bool:
    """Generates and applies the udev rule for the selected Pico."""
    try:
        result = subprocess.run(
            ["udevadm", "info", "--query=property", "--name", device.real_path],
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as exc:
        cprint(f"✗ Impossibile leggere gli attributi udev del Pico: {exc}", RED)
        return False

    properties = {}
    for line in result.stdout.splitlines():
        key, separator, value = line.partition("=")
        if separator:
            properties[key] = value

    usb_serial = properties.get("ID_SERIAL_SHORT", "")
    if not usb_serial:
        cprint(
            "✗ Il Pico selezionato non espone un seriale USB.\n"
            "  La regola udev dedicata non può essere generata in sicurezza.",
            RED,
        )
        return False

    escaped_serial = usb_serial.replace("\\", "\\\\").replace('"', '\\"')
    rule = (
        "# Generated by pico-fan setup. Do not edit manually.\n"
        f'SUBSYSTEM=="tty", ATTRS{{idVendor}}=="2e8a", '
        f'ATTRS{{serial}}=="{escaped_serial}", '
        'GROUP="dialout", MODE="0660", SYMLINK+="pico-fan"\n'
    )

    try:
        udev_dir = os.path.dirname(UDEV_RULE_FILE)
        os.makedirs(udev_dir, mode=0o755, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=udev_dir, delete=False
        ) as temporary:
            temporary.write(rule)
            temporary_path = temporary.name
        os.chmod(temporary_path, 0o644)
        os.replace(temporary_path, UDEV_RULE_FILE)

        subprocess.run(["udevadm", "control", "--reload-rules"], check=True)
        subprocess.run(
            [
                "udevadm",
                "trigger",
                "--action=change",
                "--subsystem-match=tty",
                f"--sysname-match={os.path.basename(device.real_path)}",
            ],
            check=True,
        )
    except (OSError, FileNotFoundError, subprocess.CalledProcessError) as exc:
        cprint(f"✗ Impossibile configurare la regola udev: {exc}", RED)
        return False

    cprint(
        f"✓ Regola udev configurata per il seriale USB {usb_serial}.",
        GREEN,
    )
    return True


def banner() -> None:
    cprint(rf"""
╔═══════════════════════════════════════════════════════════╗
║         PICO FAN CONTROL - Setup Wizard v{__version__:<10}    ║
║   Controllo ventola USB via Raspberry Pi Pico / RP2040    ║
╚═══════════════════════════════════════════════════════════╝
""", CYAN, bold=True)


def separator(title: str = "") -> None:
    width = 60
    if title:
        pad = (width - len(title) - 2) // 2
        cprint(f"\n{'─' * pad} {title} {'─' * pad}\n", CYAN)
    else:
        cprint("─" * width, DIM)


def ask(prompt: str, default: str = "") -> str:
    """Interactive prompt with default value support."""
    if default:
        full_prompt = f"{prompt} [{default}]: "
    else:
        full_prompt = f"{prompt}: "
    cwrite(full_prompt, WHITE, bold=True)
    sys.stdout.flush()
    try:
        answer = input().strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return default
    return answer if answer else default


def ask_yes_no(prompt: str, default: bool = True) -> bool:
    """Prompts for Y/N confirmation."""
    hint = "Y/n" if default else "y/N"
    answer = ask(f"{prompt} ({hint})", "y" if default else "n")
    return answer.lower() in ("y", "yes", "s", "si", "sì", "1", "true")


def pick_from_list(items: list, prompt: str = "Scelta") -> Optional[int]:
    """Displays a numbered list and prompts the user to select an option."""
    for i, item in enumerate(items, 1):
        cprint(f"  [{i}] {item}", WHITE)
    answer = ask(f"\n{prompt} (1-{len(items)})", "1")
    try:
        idx = int(answer) - 1
        if 0 <= idx < len(items):
            return idx
    except ValueError:
        pass
    cprint("Scelta non valida, uso la prima opzione.", YELLOW)
    return 0


# ===========================================================================
# STEP 1: Scan Pico devices
# ===========================================================================

def step_scan_devices() -> Optional[PicoDevice]:
    """Scans serial ports and prompts the user to select the Pico device."""
    separator("STEP 1 - Scansione hardware")
    cprint("Ricerca dispositivi Pico/RP2040 in /dev/serial/by-id/ ...", CYAN)

    devices = scan_devices(probe=True)

    if not devices:
        cprint(
            "\n✗ Nessun dispositivo Pico trovato!\n"
            "  Verificare che:\n"
            "  - Il cavo USB sia collegato\n"
            "  - Il firmware main.py sia caricato sul Pico\n"
            "  - Il driver cdc_acm sia caricato (modprobe cdc_acm)",
            RED,
        )
        if not ask_yes_no("\nVuoi riprovare la scansione?", default=True):
            return None
        return step_scan_devices()

    cprint(f"\n✓ Trovati {len(devices)} dispositivo/i:\n", GREEN, bold=True)

    descriptions = []
    for dev in devices:
        status = (
            f"✓ {cformat('Risponde', GREEN)} (RPM={dev.rpm}, DUTY={dev.duty}%)"
            if dev.responsive
            else f"✗ {cformat('Non risponde', RED)}"
        )
        descriptions.append(
            f"{dev.hw_id}\n"
            f"      Port: {dev.real_path} | {status}"
        )

    if len(devices) == 1:
        dev = devices[0]
        cprint(f"  Dispositivo selezionato automaticamente: {dev.real_path}", GREEN)
        return dev

    idx = pick_from_list(descriptions, "Seleziona il dispositivo da usare")
    return devices[idx] if idx is not None else None


# ===========================================================================
# STEP 2: Fan test
# ===========================================================================

def step_test_fan(device: PicoDevice) -> tuple[bool, int]:
    """Interactive fan test with variable duty cycles.
    Returns (success, optimal_duty).
    """
    separator("STEP 2 - Test ventola")

    cprint(
        f"Test della ventola su {device.real_path}\n"
        "La ventola verrà fatta girare a varie velocità.",
        CYAN,
    )

    if not ask_yes_no("Procedere con il test?", default=True):
        cprint("Test saltato.", YELLOW)
        return True, 100

    test_sequences = [
        (25,  "25% - bassa velocità"),
        (50,  "50% - velocità media"),
        (100, "100% - velocità massima"),
        (0,   "0%  - spenta"),
    ]

    def_optimal_duty = 100   # default

    try:
        with PicoAdapter(device.real_path, timeout=3.0, connect_delay=1.0) as pico:

            for duty, desc in test_sequences:
                cprint(f"\n  → Imposto {desc} ...", CYAN)

                resp = pico.send_command(f"SET {duty}")

                if resp == "OK":
                    cprint(f"    ✓ Risposta: {resp}", GREEN)
                else:
                    cprint(f"    Risposta inattesa: '{resp}'", YELLOW)

                time.sleep(2.0)

                rpm, current_duty = pico.fetch_rpm()
                rpm_resp = (
                    f"RPM:{rpm} DUTY:{current_duty}%"
                    if rpm is not None
                    else "nessuna risposta"
                )
                cprint(f"    Stato: {rpm_resp}", DIM)

        cprint("\n✓ Test completato.", GREEN, bold=True)
        ok = ask_yes_no("La ventola ha risposto correttamente?", default=True)
        if not ok:
            return False, 100

        # -------------------------------------------------------------------
        # Interactive test to determine optimal duty cycle
        # -------------------------------------------------------------------
        cprint(
            "\n  Alcune ventole raggiungono la velocità massima a un duty < 100%.\n"
            "  Puoi testare diversi valori per trovare quello ottimale.",
            DIM,
        )

        if ask_yes_no("Vuoi cercare il duty cycle ottimale per la velocità massima?", default=True):
            cprint(
                "\n  Testerò vari valori di duty. Ascolta / guarda gli RPM e\n"
                "  conferma quale produce la velocità più alta.\n",
                CYAN,
            )

            candidates = [70, 75, 80, 85, 90, 95, 100]
            results: list[tuple[int, int]] = []   # (duty, rpm)

            # Note: Direct communication with the microcontroller is used here
            # instead of the IPC socket, because the daemon is not running yet
            # at this stage of the setup process.

            try:
                with PicoAdapter(device.real_path, timeout=3.0, connect_delay=0.8) as pico:

                    for duty in candidates:
                        cprint(f"\n  → Test {duty}% ...", CYAN)
                        pico.set_duty(duty)

                        time.sleep(2.5)         # allow RPM to stabilize

                        rpm_val, current_duty = pico.fetch_rpm()
                        rpm_val = rpm_val or 0
                        rpm_raw = (
                            f"RPM:{rpm_val} DUTY:{current_duty}%"
                            if current_duty is not None
                            else f"RPM:{rpm_val}"
                        )
                        results.append((duty, rpm_val))
                        cprint(f"    {rpm_raw}  →  {rpm_val} RPM", GREEN if rpm_val > 0 else YELLOW)

                    # Turn off fan at the end of the test
                    pico.set_duty(0)

            except serial.serialutil.SerialException as exc:
                cprint(f"\n  ⚠ Errore durante il test ottimale: {exc}", YELLOW)
                return True, 100

            # Find duty cycle with highest RPM
            if results:
                best_duty, best_rpm = max(results, key=lambda x: x[1])
                cprint(
                    f"\n  Risultati rilevati:\n"
                    + "\n".join(
                        f"  {'→ ' if d == best_duty else '   '}{d:>3}%  →  {r} RPM"
                        + (" ← OTTIMALE" if d == best_duty else "")
                        for d, r in results
                    ),
                    CYAN,
                )

                if ask_yes_no(
                    f"\nUsare {best_duty}% come velocità massima della ventola?",
                    default=True,
                ):
                    def_optimal_duty = best_duty
                    cprint(f"✓ Duty massimo impostato a {def_optimal_duty}%.", GREEN, bold=True)
                else:
                    custom = ask("Inserisci manualmente il duty massimo (0-100)", str(best_duty))
                    try:
                        def_optimal_duty = max(0, min(100, int(custom)))
                    except ValueError:
                        def_optimal_duty = best_duty
                    cprint(f"✓ Duty massimo impostato a {def_optimal_duty}%.", GREEN, bold=True)

        return True, def_optimal_duty

    except serial.serialutil.SerialException as exc:
        cprint(f"\n✗ Errore durante il test: {exc}", RED)
        return False, 100


# ===========================================================================
# STEP 3: Select internal fan to monitor
# ===========================================================================

def _discover_internal_fans() -> list[dict]:
    """
    Discovers available internal fans from hwmon and /proc/acpi/ibm/fan (ThinkPad/Lenovo devices).
    Returns a list of dicts with 'label', 'type', 'path', 'rpm'.
    """
    fans = []

    # Search in /proc/acpi/ibm/fan (ThinkPad)
    ibm_fan = Path("/proc/acpi/ibm/fan")
    if ibm_fan.exists():
        rpm = read_internal_rpm_ibm(str(ibm_fan))
        fans.append({
            "label": f"ThinkPad ACPI Fan  [{ibm_fan}]  RPM={rpm if rpm is not None else 'N/A'}",
            "type":  "ibm_acpi",
            "path":  str(ibm_fan),
            "rpm":   rpm if rpm is not None else 0,
        })

    # Search in /sys/class/hwmon/*/fan*_input
    hwmon_base = Path("/sys/class/hwmon")
    if hwmon_base.exists():
        for hwmon_dir in sorted(hwmon_base.iterdir()):
            try:
                hw_name = (hwmon_dir / "name").read_text().strip()
            except OSError:
                hw_name = hwmon_dir.name

            for fan_file in sorted(hwmon_dir.glob("fan*_input")):
                rpm = read_internal_rpm_hwmon(fan_file)
                if rpm is None:
                    continue
                fans.append({
                    "label": (
                        f"hwmon:{hw_name} {fan_file.name}"
                        f"  [{fan_file}]  RPM={rpm}"
                    ),
                    "type":  "hwmon",
                    "path":  str(fan_file),
                    "rpm":   rpm,
                })

    return fans


def step_select_internal_fan() -> dict:
    """Prompts the user to select the internal fan to monitor."""
    separator("STEP 3 - Selezione ventola interna")
    cprint("Ricerca ventole interne disponibili ...\n", CYAN)

    fans = _discover_internal_fans()

    if not fans:
        cprint(
            "✗ Nessuna ventola interna rilevata.\n"
            "  Sarà usato /proc/acpi/ibm/fan come default.\n"
            "  Installare lm-sensors (apt install lm-sensors) e\n"
            "  eseguire 'sensors-detect' per abilitare i moduli.",
            YELLOW,
        )
        return {
            "type": "ibm_acpi",
            "path": "/proc/acpi/ibm/fan",
            "ibm_fan_path": "/proc/acpi/ibm/fan",
        }

    labels = [f["label"] for f in fans]
    idx = pick_from_list(labels, "Seleziona la ventola interna da monitorare")
    selected = fans[idx]
    cprint(f"\n✓ Selezionata: {selected['label']}", GREEN)
    return selected


# ===========================================================================
# STEP 4: Configure thresholds
# ===========================================================================

def step_configure_thresholds(duty_high: int = 100) -> dict:
    """Prompts the user to configure RPM thresholds."""
    separator("STEP 4 - Soglie di controllo")

    cprint(
        f"Configurazione curva ventola (duty massimo: {duty_high}%):\n"
        f"  RPM > soglia_alta  -> Ventola al {duty_high}%\n"
        "  RPM >= soglia_mid  -> Ventola al 50%\n"
        "  RPM < soglia_mid   -> Ventola spenta (0%)\n",
        CYAN,
    )

    high = ask("Soglia RPM alta  (default 4000)", "4000")
    mid  = ask("Soglia RPM media (default 2500)", "2500")

    try:
        high_val = int(high)
        mid_val  = int(mid)
    except ValueError:
        cprint("Valori non validi, uso i default.", YELLOW)
        high_val, mid_val = 4000, 2500

    if high_val <= mid_val:
        cprint("⚠ La soglia alta deve essere > soglia media. Uso valori di default.", YELLOW)
        high_val, mid_val = 4000, 2500

    cprint(
        f"\n✓ Configurazione soglie:\n"
        f"  > {high_val} RPM  → {duty_high}%\n"
        f"  {mid_val}-{high_val} RPM → 50%\n"
        f"  < {mid_val} RPM  → 0%",
        GREEN,
    )

    return {
        "rpm_threshold_high": high_val,
        "rpm_threshold_mid":  mid_val,
        "duty_high":          duty_high,
        "duty_mid":           50,
        "duty_low":           0,
    }


# ===========================================================================
# STEP 5: Save configuration
# ===========================================================================

def step_save_config(
    device: PicoDevice,
    fan_config: dict,
    thresholds: dict,
) -> bool:
    """Writes the final configuration to /etc/pico-fan/config.json."""
    separator("STEP 5 - Salvataggio configurazione")

    config = {
        "pico_serial_by_id":  device.by_id_path,
        "internal_fan_type": fan_config.get("type", "ibm_acpi"),
        "ibm_fan_path":       fan_config.get("path", "/proc/acpi/ibm/fan")
                              if fan_config.get("type") == "ibm_acpi"
                              else "/proc/acpi/ibm/fan",
        "hwmon_fan_path":     fan_config.get("path", "")
                              if fan_config.get("type") == "hwmon"
                              else "",
        "poll_interval":      2.0,
        "reconnect_interval": 5.0,
        **thresholds,
    }

    cprint("Configurazione da salvare:", CYAN)
    print(json.dumps(config, indent=2))

    if not ask_yes_no("\nConfermare e salvare?", default=True):
        cprint("Configurazione non salvata.", YELLOW)
        return False

    # Create directory if it does not exist (requires root)
    try:
        os.makedirs(CONFIG_DIR, mode=0o755, exist_ok=True)
    except PermissionError:
        cprint(
            f"✗ Permessi insufficienti per creare {CONFIG_DIR}.\n"
            f"  Eseguire il wizard come root: sudo pico-fan-setup",
            RED,
        )
        return False

    backup = None
    if os.path.exists(CONFIG_FILE):
        backup = CONFIG_FILE + ".bak"
        shutil.copy2(CONFIG_FILE, backup)
        cprint(f"  Backup configurazione precedente: {backup}", DIM)

    try:
        with open(CONFIG_FILE, "w") as f:
            json.dump(config, f, indent=2)
            f.write("\n")
        os.chmod(CONFIG_FILE, 0o644)
        cprint(f"\n✓ Configurazione salvata in {CONFIG_FILE}", GREEN, bold=True)
        return True
    except OSError as exc:
        cprint(f"✗ Errore salvataggio: {exc}", RED)
        if backup and os.path.exists(backup):
            shutil.copy2(backup, CONFIG_FILE)
        return False


# ===========================================================================
# Entry point
# ===========================================================================

def main() -> None:
    """Executes the complete configuration wizard."""
    # Clean SIGINT handling
    signal.signal(signal.SIGINT, lambda *_: (cprint("\n\nWizard interrotto.", YELLOW), sys.exit(0)))

    banner()

    cprint(
        "Questo wizard configurerà il sistema pico-fan-control.\n"
        "Avrai bisogno di:\n"
        "  • Il Raspberry Pi Pico collegato via USB con il firmware main.py caricato\n"
        "  • Privilegi root per salvare la configurazione\n",
        DIM,
    )

    if not ask_yes_no("Continuare?", default=True):
        cprint("Uscita.", YELLOW)
        sys.exit(0)

    # STEP 1: Scan and select device
    device = step_scan_devices()
    if device is None:
        cprint("\n✗ Nessun dispositivo selezionato. Uscita.", RED)
        sys.exit(1)

    # STEP 2: Fan test
    test_ok, duty_high = step_test_fan(device)
    if not test_ok:
        cprint(
            "\n⚠ Il test ventola non è andato a buon fine.\n"
            "  Verificare il firmware e il cablaggio prima di continuare.",
            YELLOW,
        )
        if not ask_yes_no("Continuare comunque?", default=False):
            sys.exit(1)
        duty_high = 100   # fallback if test failed

    # STEP 3: Internal fan
    fan_config = step_select_internal_fan()

    # STEP 4: Thresholds (passes optimal duty found during test)
    thresholds = step_configure_thresholds(duty_high=duty_high)

    # STEP 5: Save configuration
    saved = step_save_config(device, fan_config, thresholds)

    # Final summary
    separator("COMPLETATO")
    if saved:
        if configure_udev(device):
            start_service()
            cprint(
                "✓ Setup completato con successo!\n\n"
                "  Verificare lo stato:        pico-fan status\n",
                GREEN,
                bold=True,
            )
        else:
            cprint(
                "⚠ Configurazione salvata, ma il servizio non è stato avviato.\n"
                "  Correggere la configurazione udev e rieseguire il wizard.",
                YELLOW,
            )
    else:
        cprint(
            "⚠ Setup incompleto. Ricontrollare la configurazione e riprovare.",
            YELLOW,
        )


if __name__ == "__main__":
    main()
